# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8b54e6999ff1dd1807e49e20f86a759300f87c53834acae1d12e5cfe5718803472da38bb38eae033229834d27d85f5a8c2824bc0699598479050920fccbf131

test:
  secret_key_base: 56b7fbc461c9003af1e7a3eb272f524fc60c206d52c308540e03d4cd552fe312bd07bd1a1dc43f8c5bac2ca03fb62465aa3556743e72701d81ab31f9cd140da7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
